### ISSUE TITLE
Not able to add a subcollection

### ISSUE THREAD

**Issue by jmsalomr** [sichangi/node-red-contrib-cloud-firestore#22]
Hi,

I'm trying no add a subcollection but I got the following error:

msg.payload = {
    'field 1': 'a',
    'subcollection': {'field 2':'b','field 3':'c'}
}

Error: "TypeError: Cannot read property 'constructor' of null"

It works if I do:

msg.payload = {
    'field 1': 'a'
}

**Comment by sichangi** [comment]
Hello, 
Defining a subcollection / collection is done in the ``msg.firestore`` whereas the data is passed in through the ``msg.payload`` object.

So you'll have to do something like this for the collection
```js
msg.firestore = {
    "collection": "collectionName",
    "operation": "add"
};

msg.payload = {
   "field": "a"
};
```

and after getting the new documents Id, this for the subcollection

```js
msg.firestore = {
    "collection": "collectionName/documentId/subcollection",
    "operation": "add"
};

msg.payload = {
   "field": {"field 2": "b", "field 3", : "c"}
};
```
or you could generate your own docuemnt id instead of waiting on the request to complete.

**Comment by jmsalomr** [comment]
Hi,
Understood now.

msg.payload = {
   "field": {"field 2": "b", "field 3", : "c"}
};

doesn't work, but it does:

msg.payload = {
   "field 2": "b", "field 3" : "c"
};

Thanks.
