### ISSUE TITLE
Firebase Write - Error on publish message

### ISSUE THREAD

**Issue by PolSpock** [sichangi/node-red-contrib-cloud-firestore#5]
Hi,

On Node-Red 0.20.5 from docker image "nodered/node-red-docker:rpi" running on Raspberry 3 Model B+

I put Firestore Write node with a "Change" function node to pushing sample data (set String) and a "timestamp" node.

However, when i tried to publish the data i've got this error :

`Error: /usr/lib/arm-linux-gnueabihf/libstdc++.so.6: version 'GLIBCXX_3.4.21' not found (required by /data/node_modules/grpc/src/node/extension_binary/node-v57-linux-arm-glibc/grpc_node.node)`

For information, on module "node-red-contrib-firebase" i haven't problem

Thanks in advance
Regards,

**Comment by sichangi** [comment]
Hey @PolSpock , after looking around on the web, this seems to be more of a ``nodejs`` issue and how the underlying ``firebase-admin`` module interacts with it and is quite unlikely that this module is involved since it just wraps the ``firebase-admin`` module.

I'll definitely take a look at it though, but I propose you do some more research into the problem.

**Comment by sichangi** [comment]
This issue seems to have some more information about your error:-
https://github.com/nodejs/docker-node/issues/259
