### ISSUE TITLE
question about sub-collections in "node-red-contrib-cloud-firestore"

### ISSUE THREAD

**Issue by kerplunkfsd** [sichangi/node-red-contrib-cloud-firestore#52]
Hello, I'm a beginner in node-red and I'm using the "node-red-contrib-cloud-firestore" and I have a question that I can't find anywhere. In my firestore, I have a collection with two documents and within those documents I have another collection in both.

![image](https://user-images.githubusercontent.com/80550440/111003097-46576400-8365-11eb-8a7a-05907a2c8341.png)

I would like to receive data from the entire collection, with the document and the sub-collections. I know that I can receive by defining the collection on each node as: "place / House / user", but I would like to receive all data from "House" and "Mom house".

Is there a way to do this?

Thank you!

**Comment by JbIPS** [comment]
Hi,
The limitation is on Firebase by design: you're not supposed to do that. 

But you have 2 way to bypass this:
1. If you always want to get those data together, do not use a sub-collection but a array or a map as value type.
2. If you want those collections to be independent (as sub-collections), you'll need to loop. First, loop on the level 1 collection and for each key, get all the values in the linked collection. 

I use both solutions, depending on constraints and usage. Choose wisely :wink:

**Comment by kerplunkfsd** [comment]
The second way seems to solve my problems, thank you very much.

I'm really a beginner in node-red, can you give me any tips on how to do it?

Thank you again.
